"""Add item_title to Booking

Revision ID: 68f7bddacf72
Revises: 2f5c4ac9ce09
Create Date: 2026-07-30 17:22:57.654117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68f7bddacf72'
down_revision = '2f5c4ac9ce09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('item_title', sa.String(length=100), nullable=False))
        batch_op.drop_column('service')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('item_title')
        batch_op.drop_column('item_type')

    # ### end Alembic commands ###
